version: "3.7"
services:
    client:
        stdin_open: true
        build:
            context: .
        ports:
            - "3000:3000"
    caddy:
        ports:
            - 80:80
            - 443:443
        image: caddy/caddy
        volumes:
            - ./caddy/data:/data
            - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile


